<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Auto-generated Migration: Please modify to your needs!
 */
final class Version20260727094057 extends AbstractMigration
{
    public function getDescription(): string
    {
        return '';
    }

    public function up(Schema $schema): void
    {
        // this up() migration is auto-generated, please modify it to your needs
        $this->addSql('CREATE TABLE failed_job (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, job_id UUID NOT NULL, message_class VARCHAR(255) NOT NULL, error_message TEXT NOT NULL, retry_count INT NOT NULL, failed_at DATE NOT NULL, handle_at DATE DEFAULT NULL, PRIMARY KEY (id))');
    }

    public function down(Schema $schema): void
    {
        // this down() migration is auto-generated, please modify it to your needs
        $this->addSql('DROP TABLE failed_job');
    }
}
